---
Page:
  width: 680px
  height: 1013px
  resolution: 300dpi
#  offset:
#    width: 15px
#    height: 5px
Layout:

# esimene lk
-
    imageBg:
        type: image
        default: bocelli_02_square.png
        common:
            orientation: 0
        instances:
        -   x: 0
            y: 0
    imageLogo:
        type: image
        default: pl_logo_118x118.png
        common:
            orientation: 0
        instances:
        -   x: 490
            y: 30
    eventName1:
        type: text
        instances:
        -   font_name: Arial
            font_height: 34
            font_width: 14
            font_weight: 1000
            x: 36
            y: 665
    eventName2:
        type: text
        instances:
        -   font_name: Arial
            font_height: 34
            font_width: 14
            font_weight: 1000
            x: 36
            y: 710
    eventLocation:
        type: text
        instances:
        -   font_name: Arial
            font_height: 30
            font_width: 12
            font_weight: 1000
            x: 36
            y: 760
    eventDateTime:
        type: text
        instances:
        -   font_name: Arial
            font_height: 30
            font_width: 12
            font_weight: 1000
            x: 36
            y: 800
    section1:
        type: text
        instances:
        -   font_name: Arial
            font_height: 30
            font_width: 12
            font_weight: 1000
            x: 36
            y: 910
    row1:
        type: text
        instances:
        -   font_name: Arial
            font_height: 30
            font_width: 12
            font_weight: 1000
            x: 36
            y: 950
    seat1:
        type: text
        instances:
        -   font_name: Arial
            font_height: 30
            font_width: 12
            font_weight: 1000
            x: 220
            y: 950
    priceGroup1:
        type: text
        instances:
        -   font_name: Arial
            font_height: 30
            font_width: 13
            font_weight: 800
            x: 36
            y: 870
    ticketId:
        type: text
        common:
            orientation: 0
        instances:
        -   prefix: 'ID: '
            font_name: Arial
            font_height: 30
            font_width: 10
            font_weight: 500
            font_color:
                R: 255
                G: 255
                B: 255
                # A: 255
            x: 30
            y: 30
#        -   prefix: 'ID:
#            font_name: Arial
#            font_height: 30
#            font_width: 10
#            font_weight: 500
#            font_color:
#                R: 0
#                G: 0
#                B: 0
                # A: 255
#            x: 36
#            y: 835
    #       instances:
    #        -   x: 30
    #            y: 30
    #        -   x: 30
    #            y: 830
    # ticketBarCode:
    #     type: code128
    #     common:
    #         thickness: 10
    #         width: 530
    #         height: 75
    #         orientation: 0
    #         quietzone: true
    #     instances:
    #     -   x: 120
    #         y: 955
    ticketBarCode:
        type: qrcode
        common:
            scale: 6
            background:
                # R: 255
                # G: 255
                # B: 0
            foreground:
                # R: 0
                # G: 0
                # B: 0
        instances:
        -   x: 452
            y: 830

# teine lk
-
    imageBg:
        type: image
        default: bocelli_01_square.png
        common:
            orientation: 0
        instances:
        -   x: 0
            y: 0
    imageLogo:
        type: image
        default: pl_logo_118x118.png
        common:
            orientation: 0
        instances:
        -   x: 490
            y: 30
    eventName1:
        type: text
        instances:
        -   font_name: Arial
            font_height: 34
            font_width: 14
            font_weight: 1000
            x: 36
            y: 665
    eventName2:
        type: text
        instances:
        -   font_name: Arial
            font_height: 34
            font_width: 14
            font_weight: 1000
            x: 36
            y: 710
    eventLocation:
        type: text
        instances:
        -   font_name: Arial
            font_height: 30
            font_width: 12
            font_weight: 1000
            x: 36
            y: 760
    eventDateTime:
        type: text
        instances:
        -   font_name: Arial
            font_height: 30
            font_width: 12
            font_weight: 1000
            x: 36
            y: 800
    section1:
        type: text
        instances:
        -   font_name: Arial
            font_height: 30
            font_width: 12
            font_weight: 1000
            x: 36
            y: 910
    row1:
        type: text
        instances:
        -   font_name: Arial
            font_height: 30
            font_width: 12
            font_weight: 1000
            x: 36
            y: 950
    seat1:
        type: text
        instances:
        -   font_name: Arial
            font_height: 30
            font_width: 12
            font_weight: 1000
            x: 220
            y: 950
    priceGroup1:
        type: text
        instances:
        -   font_name: Arial
            font_height: 30
            font_width: 13
            font_weight: 800
            x: 36
            y: 870
    ticketId:
        type: text
        common:
            orientation: 0
        instances:
        -   prefix: 'ID: '
            font_name: Arial
            font_height: 30
            font_width: 10
            font_weight: 500
            font_color:
                R: 255
                G: 255
                B: 255
                # A: 255
            x: 30
            y: 30
#        -   prefix: 'ID:
#            font_name: Arial
#            font_height: 30
#            font_width: 10
#            font_weight: 500
#            font_color:
#                R: 0
#                G: 0
#                B: 0
                # A: 255
#            x: 36
#            y: 835
    #       instances:
    #        -   x: 30
    #            y: 30
    #        -   x: 30
    #            y: 830
    # ticketBarCode:
    #     type: code128
    #     common:
    #         thickness: 10
    #         width: 530
    #         height: 75
    #         orientation: 0
    #         quietzone: true
    #     instances:
    #     -   x: 120
    #         y: 955
    ticketBarCode:
        type: qrcode
        common:
            scale: 6
            background:
                # R: 255
                # G: 255
                # B: 0
            foreground:
                # R: 0
                # G: 0
                # B: 0
        instances:
        -   x: 452
            y: 830
